# Generated by Django 4.1.1 on 2022-09-09 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_review_favourites'),
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourite',
            old_name='myfavourites',
            new_name='myfavourite',
        ),
        migrations.AddField(
            model_name='favourite',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='favourite', to='reviews.review'),
            preserve_default=False,
        ),
    ]
