# Generated by Django 4.1.1 on 2022-09-09 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='favourites',
        ),
    ]
