# Generated by Django 4.1.1 on 2022-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_alter_review_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ImageUrl',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
